### PR TITLE
Add newline option, resolves #5

### LINKED ISSUE #5: Newline as an option
Hey woorm!

You've referred me here from https://github.com/why-jay/remark-lint-sentence-newline/issues/25 - however the plugin only supports single and double space. Would you be able to add newline as an option?

Many thanks!!

### PR DESCRIPTION
**Pull request by ThomDietrich**
Resolves #5

Feel free to adapt as you see fit.

### CODE REVIEW

**Comment by wooorm** [comment]
Looks cool! How about, accepting something an object with the following properties.

* type: `'space'` or `'newline'` (default `'space'`)
* count: `number` (default `1`)

If a string is passed in instead, treat it as `type`, and if a number is passed in, treat it as count?

That way the current system keeps working, plus we add a lot more extensibility!

**Comment by ThomDietrich** [comment]
I'm not sure about the benefits. The current solutions allows for three distinct values of the `preferred` option. The new solution would not change that but the number option is irrelevant to the newline type - seems worse to me!?

Btw. there is currently no value checking of the preferred variable. Shouldn't there be an error if the user configured `preferred: 'bolux123'`

**Comment by wooorm** [comment]
The current system allows a number to be passed in, defaulting (`null`, `undefined`, `0`, etc) to `1`.
My thinking here was that it would be useful to allow people to use multiple newlines. But I don’t really think that’s very useful.

Would it be reasonable to expect people to want to use `\t`, or `\r\n`, and should we support that?

**Comment by wooorm** [comment]
I worked on this a bit and I feel the `'newline'` option is worded a bit weird: what it actually does is check that no spaces are used! Which you could fix by adding a newline, but a tab or something else also fixes this!

How about `0` instead? Or `'none'`?

**Comment by wooorm** [comment]
@ThomDietrich Friendly ping!

**Comment by ThomDietrich** [comment]
Hey @wooorm, deeply sorry for beeing the bad conversation side for once ^^ I'm currently on vacation and will have another look at this next week, including adding my thoughts to your questions. Best! ;)

**Comment by wooorm** [comment]
Have fun on your holiday! No worries!

**Comment by wooorm** [comment]
@ThomDietrich Friendly ping!

**Comment by ThomDietrich** [comment]
I've not forgotten about this :( sorry for the long delay and thanks for keeping up the spirit. 

Regarding your comments: The goal of my addition is to check for at least one line break between sentences. The reason for that is, so that markdown paragraphs can be managed with git and GitHub in a meaningful way (see [here](https://news.ycombinator.com/item?id=4642395) for a good discussion with pros and cons). In our documentation projects we decided to go with the "newline" rule in the style guide and it turned out to be quite helpful.

The rule should hence identify everything that is not "sentence newline* sentence".
Now that I did check the code again, you are of course right. I've not covered all cases and should work on that. Still we should agree on the configuration option. I'm seeing three meaningful options:

* 1 space between sentences
* 2 spaces between sentences
* one line break between sentences

All three options should ignore multiple line breaks, as that is a valid markdown element.

How do we want to deal with tabs? Imho they should be treated as an error.

**Comment by ThomDietrich** [comment]
@wooorm wdyt?

**Comment by wooorm** [comment]
I’m so sorry this slipped through the cracks for one and a half year 😢
I reworked your changes a bit, I think the changes I made just now make sense.
Thanks for working on this previously!

**Pull request closed without merging**
